## **FASE 1: Selección de fuentes de datos**

### **Fuente A : Archivo .csv proporcionado por Kaggle**

**Nombre:** U.S. Renewable Energy Consumption

**Descripción:** Este conjunto de datos proporciona datos mensuales sobre el consumo de energía renovable en Estados Unidos desde enero de 1973 hasta diciembre de 2024, desglosados ​​por fuente de energía y sector de consumo. Los datos provienen de la Administración de Información Energética de Estados Unidos (EIA).

In [9]:
#Extracción de datos de un archivo CSV
df1 = pd.read_csv('dataset.csv', sep=',')

In [10]:
df1.rename(columns={
    'Year': 'Año',
    'Month': 'Mes',
    'Sector': 'Sector',
    'Hydroelectric Power': 'Energía Hidroeléctrica',
    'Geothermal Energy': 'Energía Geotérmica',
    'Solar Energy': 'Energía Solar',
    'Wind Energy': 'Energía Eólica',
    'Wood Energy': 'Energía de la Madera',
    'Waste Energy': 'Energía de Residuos',
    'Fuel Ethanol, Excluding Denaturant': 'Etanol Combustible (sin desnaturalizar)',
    'Biomass Losses and Co-products': 'Pérdidas y Coproductos de Biomasa',
    'Biomass Energy': 'Energía de Biomasa',
    'Total Renewable Energy': 'Energía Renovable Total',
    'Renewable Diesel Fuel': 'Diésel Renovable',
    'Other Biofuels': 'Otros Biocombustibles',
    'Conventional Hydroelectric Power': 'Energía Hidroeléctrica Convencional',
    'Biodiesel': 'Biodiésel'
}, inplace=True)

In [11]:
df1.head()

,Año,Mes,Sector,Energía Hidroeléctrica,Energía Geotérmica,Energía Solar,Energía Eólica,Energía de la Madera,Energía de Residuos,Etanol Combustible (sin desnaturalizar),Pérdidas y Coproductos de Biomasa,Energía de Biomasa,Energía Renovable Total,Diésel Renovable,Otros Biocombustibles,Energía Hidroeléctrica Convencional,Biodiésel
0,1973,1,Commerical,0.00,0.00,0.0,0.0,0.570,0.000,0.0,0.0,0.570,0.570,0.0,0.0,0.000,0.0
1,1973,1,Electric Power,0.00,0.49,0.0,0.0,0.054,0.157,0.0,0.0,0.211,89.223,0.0,0.0,88.522,0.0
2,1973,1,Industrial,1.04,0.00,0.0,0.0,98.933,0.000,0.0,0.0,98.933,99.973,0.0,0.0,0.000,0.0
3,1973,1,Residential,0.00,0.00,0.0,0.0,30.074,0.000,0.0,0.0,0.000,30.074,0.0,0.0,0.000,0.0
4,1973,1,Transportation,0.00,0.00,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0

### **Fuente B : Api proporcionado por Kaggle**

**Nombre:** Electricity Production Dataset

**Descripción:** Este conjunto de datos ofrece una visión general completa de los datos de producción eléctrica mundial que abarcan 48 países entre 2010 y 2023. Proporciona información valiosa sobre el balance, la producción y el valor de la generación eléctrica en diferentes regiones durante el período especificado. Centrado en la producción eléctrica, este conjunto de datos resulta fundamental para analistas energéticos, responsables políticos e investigadores que buscan comprender las tendencias energéticas globales, identificar patrones y desarrollar estrategias para la producción y el consumo de energía sostenibles.

**URL:** https://www.kaggle.com/datasets/sazidthe1/global-electricity-production

In [ ]:
! pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.7.4.2)
Requirement already satisfied: bleach in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (78.1.0)
Requirement already satisfied: six>=1.10 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: colorama in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\ACER NITRO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [40]:
import os
import json
import zipfile
import pandas as pd
from kaggle.api.kaggle_api_extended import KaggleApi

def extract_from_api():
    # Leer el archivo kaggle.json desde la ruta del proyecto
    with open('.kaggle/kaggle.json', 'r') as f:
        token = json.load(f)
    os.environ['KAGGLE_USERNAME'] = token['username']
    os.environ['KAGGLE_KEY'] = token['key']

    # Inicializar y autenticar la API de Kaggle
    api = KaggleApi()
    api.authenticate()

    # Descargar el archivo ZIP
    dataset_path = 'sazidthe1/global-electricity-production'
    zip_name = 'global-electricity-production.zip'
    extract_folder = 'tmp_kaggle_data'

    if not os.path.exists(zip_name):
        api.dataset_download_files(dataset_path, path='.', unzip=False)

    # Extraer el CSV del ZIP
    with zipfile.ZipFile(zip_name, 'r') as zip_ref:
        zip_ref.extractall(extract_folder)
        csv_file = [f for f in zip_ref.namelist() if f.endswith('.csv')][0]

    df = pd.read_csv(os.path.join(extract_folder, csv_file))
    return df

In [41]:
df = extract_from_api()
df.head()

Dataset URL: https://www.kaggle.com/datasets/sazidthe1/global-electricity-production

,country_name,date,parameter,product,value,unit
0,Australia,12/1/2023,Net Electricity Production,Electricity,22646.1901,GWh
1,Australia,12/1/2023,Net Electricity Production,Total Combustible Fuels,13397.9356,GWh
2,Australia,12/1/2023,Net Electricity Production,"Coal, Peat and Manufactured Gases",9768.5223,GWh
3,Australia,12/1/2023,Net Electricity Production,Oil and Petroleum Products,289.5415,GWh
4,Australia,12/1/2023,Net Electricity Production,Natural Gas,3091.9272,GWh