## **FASE 1: Selección de fuentes de datos**

### **Fuente A : Archivo .csv proporcionado por Kaggle**

**Nombre:** U.S. Renewable Energy Consumption

**Descripción:** Este conjunto de datos proporciona datos mensuales sobre el consumo de energía renovable en Estados Unidos desde enero de 1973 hasta diciembre de 2024, desglosados ​​por fuente de energía y sector de consumo. Los datos provienen de la Administración de Información Energética de Estados Unidos (EIA).

In [3]:
import pandas as pd

In [4]:
#Extracción de datos de un archivo CSV
df1 = pd.read_csv('dataset.csv', sep=',')

In [5]:
df1.rename(columns={
    'Year': 'Año',
    'Month': 'Mes',
    'Sector': 'Sector',
    'Hydroelectric Power': 'Energía Hidroeléctrica',
    'Geothermal Energy': 'Energía Geotérmica',
    'Solar Energy': 'Energía Solar',
    'Wind Energy': 'Energía Eólica',
    'Wood Energy': 'Energía de la Madera',
    'Waste Energy': 'Energía de Residuos',
    'Fuel Ethanol, Excluding Denaturant': 'Etanol Combustible (sin desnaturalizar)',
    'Biomass Losses and Co-products': 'Pérdidas y Coproductos de Biomasa',
    'Biomass Energy': 'Energía de Biomasa',
    'Total Renewable Energy': 'Energía Renovable Total',
    'Renewable Diesel Fuel': 'Diésel Renovable',
    'Other Biofuels': 'Otros Biocombustibles',
    'Conventional Hydroelectric Power': 'Energía Hidroeléctrica Convencional',
    'Biodiesel': 'Biodiésel'
}, inplace=True)

In [6]:
df1.head()

,Año,Mes,Sector,Energía Hidroeléctrica,Energía Geotérmica,Energía Solar,Energía Eólica,Energía de la Madera,Energía de Residuos,Etanol Combustible (sin desnaturalizar),Pérdidas y Coproductos de Biomasa,Energía de Biomasa,Energía Renovable Total,Diésel Renovable,Otros Biocombustibles,Energía Hidroeléctrica Convencional,Biodiésel
0,1973,1,Commerical,0.00,0.00,0.0,0.0,0.570,0.000,0.0,0.0,0.570,0.570,0.0,0.0,0.000,0.0
1,1973,1,Electric Power,0.00,0.49,0.0,0.0,0.054,0.157,0.0,0.0,0.211,89.223,0.0,0.0,88.522,0.0
2,1973,1,Industrial,1.04,0.00,0.0,0.0,98.933,0.000,0.0,0.0,98.933,99.973,0.0,0.0,0.000,0.0
3,1973,1,Residential,0.00,0.00,0.0,0.0,30.074,0.000,0.0,0.0,0.000,30.074,0.0,0.0,0.000,0.0
4,1973,1,Transportation,0.00,0.00,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.000,0.0,0.0,0.000,0.0

### **Fuente B : Api proporcionado por Kaggle**

**Nombre:** Electricity Production Dataset

**Descripción:** Este conjunto de datos ofrece una visión general completa de los datos de producción eléctrica mundial que abarcan 48 países entre 2010 y 2023. Proporciona información valiosa sobre el balance, la producción y el valor de la generación eléctrica en diferentes regiones durante el período especificado. Centrado en la producción eléctrica, este conjunto de datos resulta fundamental para analistas energéticos, responsables políticos e investigadores que buscan comprender las tendencias energéticas globales, identificar patrones y desarrollar estrategias para la producción y el consumo de energía sostenibles.

**URL:** https://www.kaggle.com/datasets/sazidthe1/global-electricity-production

In [8]:
! pip install kaggle

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: kaggle in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (1.7.4.2)
Requirement already satisfied: bleach in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2025.1.31)
Requirement already satisfied: charset-normalizer in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (3.4.1)
Requirement already satisfied: idna in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (78.1.0)
Requirement already satisfied: six>=1.10 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (2.3.0)
Requirement already satisfied: webencodings in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: colorama in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\ACER NITRO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [9]:
import os
import json
import zipfile
import pandas as pd
from kaggle.api.kaggle_api_extended import KaggleApi

def extract_from_api():
    # Leer el archivo kaggle.json desde la ruta del proyecto
    with open('.kaggle/kaggle.json', 'r') as f:
        token = json.load(f)
    os.environ['KAGGLE_USERNAME'] = token['username']
    os.environ['KAGGLE_KEY'] = token['key']

    # Inicializar y autenticar la API de Kaggle
    api = KaggleApi()
    api.authenticate()

    # Descargar el archivo ZIP
    dataset_path = 'sazidthe1/global-electricity-production'
    zip_name = 'global-electricity-production.zip'
    extract_folder = 'tmp_kaggle_data'

    if not os.path.exists(zip_name):
        api.dataset_download_files(dataset_path, path='.', unzip=False)

    # Extraer el CSV del ZIP
    with zipfile.ZipFile(zip_name, 'r') as zip_ref:
        zip_ref.extractall(extract_folder)
        csv_file = [f for f in zip_ref.namelist() if f.endswith('.csv')][0]

    df = pd.read_csv(os.path.join(extract_folder, csv_file))
    return df

df2 = extract_from_api()

In [10]:
df2.rename(columns={
    "country_name": "Nombre del País",
    "date": "Fecha",
    "parameter": "Parámetro",
    "product": "Producto",
    "value" : "Valor",
    "unit": "Unidad"
}, inplace=True)

df2.head()

,Nombre del País,Fecha,Parámetro,Producto,Valor,Unidad
0,Australia,12/1/2023,Net Electricity Production,Electricity,22646.1901,GWh
1,Australia,12/1/2023,Net Electricity Production,Total Combustible Fuels,13397.9356,GWh
2,Australia,12/1/2023,Net Electricity Production,"Coal, Peat and Manufactured Gases",9768.5223,GWh
3,Australia,12/1/2023,Net Electricity Production,Oil and Petroleum Products,289.5415,GWh
4,Australia,12/1/2023,Net Electricity Production,Natural Gas,3091.9272,GWh

## **FASE 2: Proceso de ETL (Extracción, Transformación y Carga)**

In [54]:
! pip install numpy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.2.4)
Requirement already satisfied: pandas in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (2.2.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\ACER NITRO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

### **2.1 - Limpieza de datos**

### **Fuente A**

In [11]:
#Ver forma y tipo de datos
print("Forma de df1:", df1.shape)

print("\n Tipos de datos en df1:")
print(df1.dtypes)

Forma de df1: (3065, 17)

 Tipos de datos en df1:
Año                                          int64
Mes                                          int64
Sector                                      object
Energía Hidroeléctrica                     float64
Energía Geotérmica                         float64
Energía Solar                              float64
Energía Eólica                             float64
Energía de la Madera                       float64
Energía de Residuos                        float64
Etanol Combustible (sin desnaturalizar)    float64
Pérdidas y Coproductos de Biomasa          float64
Energía de Biomasa                         float64
Energía Renovable Total                    float64
Diésel Renovable                           float64
Otros Biocombustibles                      float64
Energía Hidroeléctrica Convencional        float64
Biodiésel                                  float64
dtype: object

In [12]:
#Revisar valores nulos por columna

print("Nulos en df1:")
print(df1.isnull().sum())

Nulos en df1:
Año                                        0
Mes                                        0
Sector                                     0
Energía Hidroeléctrica                     0
Energía Geotérmica                         0
Energía Solar                              0
Energía Eólica                             0
Energía de la Madera                       0
Energía de Residuos                        0
Etanol Combustible (sin desnaturalizar)    0
Pérdidas y Coproductos de Biomasa          0
Energía de Biomasa                         0
Energía Renovable Total                    0
Diésel Renovable                           0
Otros Biocombustibles                      0
Energía Hidroeléctrica Convencional        0
Biodiésel                                  0
dtype: int64

In [13]:
#Revisar si hay duplicados

print("🔁 Duplicados en df1:", df1.duplicated().sum())

🔁 Duplicados en df1: 0

In [14]:
#Convertimos una columna de fecha compuesta a datetime
df1['fecha'] = pd.to_datetime(df1['Año'].astype(str) + '-' + df1['Mes'].astype(str) + '-01')

In [15]:
df1.head(2)

,Año,Mes,Sector,Energía Hidroeléctrica,Energía Geotérmica,Energía Solar,Energía Eólica,Energía de la Madera,Energía de Residuos,Etanol Combustible (sin desnaturalizar),Pérdidas y Coproductos de Biomasa,Energía de Biomasa,Energía Renovable Total,Diésel Renovable,Otros Biocombustibles,Energía Hidroeléctrica Convencional,Biodiésel,fecha
0,1973,1,Commerical,0.0,0.00,0.0,0.0,0.570,0.000,0.0,0.0,0.570,0.570,0.0,0.0,0.000,0.0,1973-01-01
1,1973,1,Electric Power,0.0,0.49,0.0,0.0,0.054,0.157,0.0,0.0,0.211,89.223,0.0,0.0,88.522,0.0,1973-01-01

### **Fuente B**

In [16]:
#Ver forma y tipo de datos
print("Forma de df1:", df2.shape)

print("\n Tipos de datos en df2:")
print(df2.dtypes)

Forma de df1: (121074, 6)

 Tipos de datos en df2:
Nombre del País     object
Fecha               object
Parámetro           object
Producto            object
Valor              float64
Unidad              object
dtype: object

In [17]:
#Convertir fecha a tipo datetime
df2['Fecha'] = pd.to_datetime(df2['Fecha'], errors='coerce')

In [18]:
#Revisar valores nulos por columna

print("Nulos en df2:")
print(df2.isnull().sum())

Nulos en df2:
Nombre del País     0
Fecha               0
Parámetro           0
Producto            0
Valor              14
Unidad              0
dtype: int64

In [19]:
#Eliminamos nulos

df2 = df2.dropna(subset=['Valor'])

print("Filas con valores nulos en 'valor' eliminadas.")
print("Nueva forma de df2:", df2.shape)

Filas con valores nulos en 'valor' eliminadas.
Nueva forma de df2: (121060, 6)

In [20]:
#Revisar si hay duplicados

print("Duplicados en df1:", df2.duplicated().sum())

Duplicados en df1: 0

### **2.2. Creación de base de datos**

### **Vamos a crear una dimensión de fecha que me relacione ambas bases de datos**

In [21]:
#vamos a indentificar las fecha maximay minima de cada dataframe
print("Fecha mínima en df1:", df1['fecha'].min())
print("Fecha máxima en df1:", df1['fecha'].max())
print("Fecha mínima en df2:", df2['Fecha'].min())
print("Fecha máxima en df2:", df2['Fecha'].max())

Fecha mínima en df1: 1973-01-01 00:00:00
Fecha máxima en df1: 2024-01-01 00:00:00
Fecha mínima en df2: 2010-01-01 00:00:00
Fecha máxima en df2: 2023-12-01 00:00:00

In [22]:
import pandas as pd

# Rango de fechas
fecha_inicio = "1973-01-01"
fecha_fin = "2024-01-01"

# Generar rango de fechas
dim_fecha = pd.DataFrame({
    "fecha": pd.date_range(start=fecha_inicio, end=fecha_fin, freq="D")
})

# Extraer atributos temporales
dim_fecha["año"] = dim_fecha["fecha"].dt.year
dim_fecha["mes"] = dim_fecha["fecha"].dt.month
dim_fecha["día"] = dim_fecha["fecha"].dt.day
dim_fecha["nombre_mes"] = dim_fecha["fecha"].dt.month_name()
dim_fecha["nombre_día"] = dim_fecha["fecha"].dt.day_name()
dim_fecha["número_semana"] = dim_fecha["fecha"].dt.isocalendar().week
dim_fecha["trimestre"] = dim_fecha["fecha"].dt.quarter
dim_fecha["es_fin_de_semana"] = dim_fecha["nombre_día"].isin(["Saturday", "Sunday"])
dim_fecha["es_día_laboral"] = ~dim_fecha["es_fin_de_semana"]

In [23]:
dim_fecha.head(4)

,fecha,año,mes,día,nombre_mes,nombre_día,número_semana,trimestre,es_fin_de_semana,es_día_laboral
0,1973-01-01,1973,1,1,January,Monday,1,1,False,True
1,1973-01-02,1973,1,2,January,Tuesday,1,1,False,True
2,1973-01-03,1973,1,3,January,Wednesday,1,1,False,True
3,1973-01-04,1973,1,4,January,Thursday,1,1,False,True

### **Creamos una base datos relacional de MySQL en el servicio de : https://railway.app/ y nos conectamos a ella**

In [83]:
pip install dotenv pymysql

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: dotenv in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (0.9.9)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: python-dotenv in c:\users\acer nitro\appdata\local\packages\pythonsoftwarefoundation.python.3.12_qbz5n2kfra8p0\localcache\local-packages\python312\site-packages (from dotenv) (1.1.0)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\ACER NITRO\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [24]:
#Nos conectamos a la base de datos MySQL creadaa en railway
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine

# Cargar las variables del archivo .env
load_dotenv()

# Obtener las variables desde el entorno
usuario = os.getenv("MYSQL_USER")
contraseña = os.getenv("MYSQL_PASSWORD")
host = os.getenv("MYSQL_HOST")
puerto = os.getenv("MYSQL_PORT")
base_de_datos = os.getenv("MYSQL_DB")

# Crear el engine para conectarte
engine = create_engine(f"mysql+pymysql://{usuario}:{contraseña}@{host}:{puerto}/{base_de_datos}")

**Cargamos la tabla de fechas**

In [25]:
#Creamos la tabla de fechas en la base de datos
dim_fecha.to_sql('dim_fecha', con=engine, if_exists='replace', index=False)
print("Tabla 'dim_fecha' creada en la base de datos MySQL.")

Tabla 'dim_fecha' creada en la base de datos MySQL.

In [26]:
#validamos la creación de la tabla
query = "SELECT * FROM dim_fecha LIMIT 5;"
df_fecha = pd.read_sql(query, con=engine)
print(df_fecha.head())

       fecha   año  mes  día nombre_mes nombre_día  número_semana  trimestre  \
0 1973-01-01  1973    1    1    January     Monday              1          1
1 1973-01-02  1973    1    2    January    Tuesday              1          1
2 1973-01-03  1973    1    3    January  Wednesday              1          1
3 1973-01-04  1973    1    4    January   Thursday              1          1
4 1973-01-05  1973    1    5    January     Friday              1          1

   es_fin_de_semana  es_día_laboral
0                 0               1
1                 0               1
2                 0               1
3                 0               1
4                 0               1

**Cargamos la tabla de Renewable Energy Consumption (df1)**

In [27]:
#Creamos la tabla df1 en la base de datos
df1.to_sql('dim_renovables', con=engine, if_exists='replace', index=False)
print("Tabla 'dim_renovables' creada en la base de datos MySQL.")
#validamos la creación de la tabla.
query = "SELECT * FROM dim_renovables LIMIT 5;"
df_renovables = pd.read_sql(query, con=engine)
print(df_renovables.head())

Tabla 'dim_renovables' creada en la base de datos MySQL.
    Año  Mes          Sector  Energía Hidroeléctrica  Energía Geotérmica  \
0  1973    1      Commerical                    0.00                0.00
1  1973    1  Electric Power                    0.00                0.49
2  1973    1      Industrial                    1.04                0.00
3  1973    1     Residential                    0.00                0.00
4  1973    1  Transportation                    0.00                0.00

   Energía Solar  Energía Eólica  Energía de la Madera  Energía de Residuos  \
0            0.0             0.0                 0.570                0.000
1            0.0             0.0                 0.054                0.157
2            0.0             0.0                98.933                0.000
3            0.0             0.0                30.074                0.000
4            0.0             0.0                 0.000                0.000

   Etanol Combustible (sin desnaturalizar)  Pérdidas y Coproductos de Biomasa  \
0                                      0.0                                0.0
1                                      0.0                                0.0
2                                      0.0                                0.0
3                                      0.0                                0.0
4                                      0.0                                0.0

   Energía de Biomasa  Energía Renovable Total  Diésel Renovable  \
0               0.570                    0.570               0.0
1               0.211                   89.223               0.0
2              98.933                   99.973               0.0
3               0.000                   30.074               0.0
4               0.000                    0.000               0.0

   Otros Biocombustibles  Energía Hidroeléctrica Convencional  Biodiésel  \
0                    0.0                                0.000        0.0
1                    0.0                               88.522        0.0
2                    0.0                                0.000        0.0
3                    0.0                                0.000        0.0
4                    0.0                                0.000        0.0

       fecha
0 1973-01-01
1 1973-01-01
2 1973-01-01
3 1973-01-01
4 1973-01-01

**Cargamos la tabla de Electricity Production Dataset**

In [46]:
df2.to_sql('dim_electricidad', con=engine, if_exists='replace', index=False)
print("Tabla 'dim_electricidad' creada en la base de datos MySQL.")
#validamos la creación de la tabla.
query = "SELECT * FROM dim_electricidad LIMIT 5;"
df_electricity = pd.read_sql(query, con=engine)

Tabla 'dim_electricidad' creada en la base de datos MySQL.

In [ ]:
#COMANDOS PARA ELIMINAR LAS TABLAS CREADAS EN LA BASE DE DATOS
'''from sqlalchemy import text

with engine.begin() as connection:
    connection.execute(text("DROP TABLE IF EXISTS Dim_Electricity;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_Electricity;"))
    connection.execute(text("DROP TABLE IF EXISTS dim_electricidad;"))
    print("✅ Tablas eliminadas (si existían).")


'''

✅ Tabla 'dim_Electricity' eliminada correctamente (si existía).

A continuación, se muestra una captura como evidencia de la creación de las tablas `dim_fecha`, `dim_renovables` y `dim_Electricidad` creada y cargada exitosamente en la base de datos MySQL:

![Base de datos](./Imagenes/Base_de_datos.jpg)